"""Ports owned by the application; adapters depend on these contracts."""
from datetime import date
from typing import Protocol
from app.domain.models import Case, Factor
from app.application.rag_contracts import EvidenceQuery, EvidenceHit, AnswerDraft
from app.application.agent_contracts import AgentTurn
from app.application.ruleset_contracts import RulesetExtractionResult


class PdfReader(Protocol):
    def read(self, data: bytes) -> list[dict]: ...


class FieldExtractor(Protocol):
    def extract(self, pages: list[dict], ruleset: dict) -> list[Factor]: ...


class RulesetExtractor(Protocol):
    def extract(
        self,
        pages: list[dict],
        *,
        source_name: str,
        expected_locality: str,
    ) -> RulesetExtractionResult: ...


class ReviewRepository(Protocol):
    def initialize(self) -> None: ...
    def list_cases(self) -> list[tuple[Case, str]]: ...
    def get_case(self, case_id: str) -> Case: ...
    def save_case(self, case: Case, action: str, *, new: bool = False) -> Case: ...
    def get_rules(self, ruleset_id: str) -> dict: ...
    def list_rules(self) -> list[dict]: ...
    def add_rules(self, ruleset: dict) -> dict: ...
    def save_confirmed_ruleset(
        self,
        ruleset: dict,
        document_id: str,
        valid_from: date,
        valid_to: date,
    ) -> dict: ...
    def save_document(self, data: bytes, name: str, pages: list[dict]) -> str: ...
    def get_document(self, document_id: str) -> dict: ...
    def save_evidence_document(self, data: bytes, name: str, pages: list[dict], ruleset: dict, valid_from: date, valid_to: date) -> dict: ...
    def list_evidence_documents(self, ruleset_id: str) -> list[dict]: ...
    def evidence_sources(self, query: EvidenceQuery) -> list[dict]: ...
    def audit(self, case_id: str) -> list[dict]: ...
    def snapshot(self, case_id: str, audit_id: int) -> dict: ...


class ExtractionUnavailable(RuntimeError):
    """Safe, user-facing failure without a cloud response or credential dump."""


class RevisionConflict(ValueError):
    pass


class EvidenceRetriever(Protocol):
    def retrieve(self, query: EvidenceQuery) -> list[EvidenceHit]: ...


class EvidencePublisher(Protocol):
    def sync_ruleset(self, ruleset_id: str) -> dict: ...
    def status(self) -> dict: ...


class EvidenceAnswerer(Protocol):
    def answer(self, question: str, hits: list[EvidenceHit]) -> AnswerDraft: ...


class AgentModel(Protocol):
    def next_turn(self, context: dict, history: list[dict], tools: list[dict]) -> AgentTurn: ...


class PublicDataLookup(Protocol):
    def catalog(self) -> dict: ...
    def lookup(self, locality: str, source_key: str, school_year: int | None) -> dict: ...
