"""Ports owned by the application; adapters depend on these contracts."""
from typing import Protocol
from app.domain.models import Case, Factor


class PdfReader(Protocol):
    def read(self, data: bytes) -> list[dict]: ...


class FieldExtractor(Protocol):
    def extract(self, pages: list[dict], ruleset: dict) -> list[Factor]: ...


class ReviewRepository(Protocol):
    def initialize(self) -> None: ...
    def list_cases(self) -> list[tuple[Case, str]]: ...
    def get_case(self, case_id: str) -> Case: ...
    def save_case(self, case: Case, action: str, *, new: bool = False) -> Case: ...
    def get_rules(self, ruleset_id: str) -> dict: ...
    def list_rules(self) -> list[dict]: ...
    def add_rules(self, ruleset: dict) -> dict: ...
    def save_document(self, data: bytes, name: str, pages: list[dict]) -> str: ...
    def get_document(self, document_id: str) -> dict: ...
    def audit(self, case_id: str) -> list[dict]: ...
    def snapshot(self, case_id: str, audit_id: int) -> dict: ...


class ExtractionUnavailable(RuntimeError):
    """Safe, user-facing failure without a cloud response or credential dump."""


class RevisionConflict(ValueError):
    pass
